name: Terraform
description: Installs and executes terraform with a specific action.
inputs:
  terraform_deploy_role:
    description: "The IAM role to deploy as"
    required: true
  terraform_workspace:
    description: "The Terraform workspace to use (optional)"
    required: false

runs:
  using: "composite"
  steps:
    - name: Cache Terraform Providers
      id: cache-terraform
      uses: actions/cache@v4
      with:
        path: .terraform
        key: ${{ runner.os }}-${{ inputs.environment }}-${{ hashFiles('**/.terraform.lock.hcl') }}

    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        audience: sts.amazonaws.com # set default value to work around https://github.com/aws-actions/configure-aws-credentials/issues/271#issuecomment-1401481855
        aws-region: eu-west-2
        role-to-assume: ${{ inputs.terraform_deploy_role }}

    - name: Terraform Init
      id: init
      shell: bash
      run: |
        terraform version
        terraform init -input=false
        # Select the specified workspace to ensure Env0 and GitHub Actions share the same state file
        # This allows both environments to work with the same Terraform state stored in S3
        if [ -n "${{ inputs.terraform_workspace }}" ]; then
          terraform workspace select "${{ inputs.terraform_workspace }}" || terraform workspace new "${{ inputs.terraform_workspace }}"
        fi
